version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y libcgal-dev liboce-foundation-dev cmake git
             libhdf5-dev libblas-dev liblapack-dev g++ gfortran

#version: 2
#jobs:
#  build:
#    docker:
#      - image: debian:stretch
#    steps:
#      - checkout
#      - run:
#         command: |
#           
#  test:
#    - run:
#       command: echo hello world
#
#workflows:
#  version: 2
#  build_and_test:
#    jobs:
#      - build
#      - test
