version: 2
jobs:
  build:
    docker:
      - image: debian:stretch	
    steps:
      - checkout:
      - run:
      	  name: Update image
      	  command: sudo apt-get install libcgal-dev liboce-foundation-dev cmake git \ &&
	  	   libhdf5-dev libblas-dev liblapack-dev g++ gfortran
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current date
	  command: date

workflows:
  version: 2
    build_and_test:
      jobs:
         - build
	 - test:
    	    requires:
	      - build